### PR TITLE
fixed deposit value calculation, refactoring

### LINKED ISSUE #383: Incorrect "Current value" on second farming deposit
On POOLS & FARMS, when you deposit your farming NFT into a second farm, the "current value" field appears to count the value twice.

image

### PR DESCRIPTION
**Pull request by obsivac-cleevio**
- Fixes #383

### CODE REVIEW

File: src/utils/farms/deposits.ts [hunk 1]
```diff
@@ -83,19 +78,77 @@ export const useAllUserDeposits = () => {
...
+      totalIssuances.some((q) => !q.data)
+    )
+      return defaultValue
+
+    const shareTokenIssuance = totalIssuances.find(
+      (ti) => ti.data?.token.toString() === shareToken.data.token.toString(),
+    )?.data?.total
+
+    if (!shareTokenIssuance) {
+      console.log("Could not calculate deposit balances")
```
Comment (vkulinich-cl) [inline src/utils/farms/deposits.ts:122]: console log

**Review by vkulinich-cl — APPROVED** [review]
